name: chromatic
on:
  push:
    branches:
      - master
    paths:
      - "packages/chromatic/**"
      - ".github/workflows/chromatic.yml"

jobs:
  build:
    name: docker build + push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: GitHub registry build + push
        uses: whoan/docker-build-with-cache-action@master
        with:
          context: packages/chromatic
          registry: docker.pkg.github.com
          image_name: hivehr/github-actions/chromatic
          image_tag: latest
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
