name: Publish Packages

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      
    - name: "[get-jira-issue] Build Docker image"
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/hivehr/github-actions/get-jira-issue:${{ github.ref }}
      working-directory: packages/get-jira-issue
    
    - name: "[get-jira-issue] Push to Package Registry"
      run: docker push docker.pkg.github.com/phanatic/repo/app:1.0.0
      working-directory: packages/get-jira-issue
      
