name: Publish Package

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/hivehr/github-actions/get-jira-issue:${{ github.ref }}
    
    - name: Push to Package Registry
      run: docker push docker.pkg.github.com/phanatic/repo/app:1.0.0
