name: github-push-action
on:
  push:
    branches:
      - master
    paths:
      - "packages/github-push-action/*"
      - ".github/workflows/github-push-action.yml"

jobs:
  build:
    name: docker build + push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Checkout submodule code
      - name: git submodule sync --recursive
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: GitHub registry build + push
        uses: whoan/docker-build-with-cache-action@master
        with:
          context: packages/github-push-action
          registry: docker.pkg.github.com
          image_name: hivehr/github-actions/github-push-action
          image_tag: latest
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      # TODO: Remove once we can use GitHub Registry images in Actions
      - name: DockerHub registry build + push
        uses: whoan/docker-build-with-cache-action@master
        with:
          context: packages/github-push-action
          image_name: hivehr/github-actions-github-push-action
          image_tag: latest
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
