name: terraform-github-actions
on:
  push:
    branches:
      - master
    paths:
      - "packages/terraform-github-actions/**"
      - ".github/workflows/terraform-github-actions.yml"

jobs:
  build:
    name: docker build + push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: GitHub registry build + push
        uses: whoan/docker-build-with-cache-action@master
        with:
          context: packages/terraform-github-actions
          registry: docker.pkg.github.com
          image_name: hivehr/github-actions/terraform-github-actions
          image_tag: latest
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      # TODO: Remove once we can use GitHub Registry images in Actions
      - name: DockerHub registry build + push
        uses: whoan/docker-build-with-cache-action@master
        with:
          context: packages/terraform-github-actions
          image_name: hivehr/github-actions-terraform-github-actions
          image_tag: latest
          registry: "${{ secrets.DOCKER_REGISTRY_URL }}"
          username: "${{ secrets.DOCKER_REGISTRY_USERNAME }}"
          password: "${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}"
