name: update-pr
on:
  push:
    branches:
      - master
    paths:
      - "packages/update-pr/**"
      - ".github/workflows/update-pr.yml"

jobs:
  build:
    name: docker build + push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitHub registry build + push
        uses: whoan/docker-build-with-cache-action@master
        with:
          context: packages/update-pr
          registry: docker.pkg.github.com
          image_name: hivehr/github-actions/update-pr
          image_tag: latest
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
